### ISSUE TITLE
Problem with the angular resolution of ARS548 RDI	

### ISSUE THREAD

**Issue by ZHOUYI1023** [adept-thu/Dual-Radar#1]
In your table, there is a confusion between the accuracy and resolution of ARS548 RDI. The angular resolution in the radar spec is represented by the half-power beam width [1]. 

The value should be
Azimuth beam width (3 dB) 1.2°… 1.68° - 1.2°@0…±15° - 1.68°@±45°
Elevation beam width (3 dB) 2.3°

Additionallly, the FoV should be range-dependent

Elevation angle augmentation (field of view FoV)
±4°… ±14° - ±4°@300m - ±14°@<100m
±20° keep out zone

[1] https://www.radartutorial.eu/01.basics/Angular%20Resolution.en.html

**Comment by liulin813** [comment]
Thank you for your feedback. We have now updated the README document as per your suggestions.

**Comment by ylwhxht** [comment]
> In your table, there is a confusion between the accuracy and resolution of ARS548 RDI. The angular resolution in the radar spec is represented by the half-power beam width [1].
> 
> The value should be Azimuth beam width (3 dB) 1.2°… 1.68° - 1.2°@0…±15° - 1.68°@±45° Elevation beam width (3 dB) 2.3°
> 
> Additionallly, the FoV should be range-dependent
> 
> Elevation angle augmentation (field of view FoV) ±4°… ±14° - ±4°@300M - ±14°@<100m ±20° keep out zone
> 
> [1] https://www.radartutorial.eu/01.basics/Angular%20Resolution.en.html

We also encountered the same problem. Have you finally resolved it？
