### ISSUE TITLE
ImportError: cannot import name 'M2PillarVFE' from 'pcdet.models.backbones_3d.vfe.M2Fusion_vfe'

### ISSUE THREAD

**Issue by c-yyyy** [adept-thu/Dual-Radar#12]
pcdet.models.backbones_3d.vfe.M2Fusion_vfe下似乎并没有M2PillarVFE，是暂时还没有来得及更新吗

**Comment by liulin813** [comment]
we had updated the code

**Comment by liulin813** [comment]
![image](https://github.com/adept-thu/Dual-Radar/assets/94374055/9a554f6e-f5a9-483b-aed7-1959757e9660)
