### ISSUE TITLE
arbe、ars、Lidar三种模态点云保存时对应坐标系

### ISSUE THREAD

**Issue by c-yyyy** [adept-thu/Dual-Radar#13]
![image](https://github.com/adept-thu/Dual-Radar/assets/109772145/219051b3-84ca-4308-84f4-c10fe6bc648e)
想知道这三种模态的点云文件保存时是否都是以Lidar坐标系作为坐标系的吗。因为似乎代码里获得ars、arbe两种数据的3D包围框标签是直接用lidar的包围框，如下所示：
![image](https://github.com/adept-thu/Dual-Radar/assets/109772145/b09c3f1b-4861-45fe-ac4a-9e5f60000dd0)

**Comment by c-yyyy** [comment]
应该是源码其他地方已有arbe或ars点云坐标系转换至lidar坐标系，所以数据模态还是不一样的。

**Comment by Bryceder** [comment]
请问您这边有没有遇到radar模型推理阶段出现bbox角度和位置偏移的问题呢？即使使用lidar模型也存在这个现象。我遇到一个奇怪的现象在一定范围内，bbox会偏差90度，但是不在这个范围内的则是正常的。
![12344](https://github.com/adept-thu/Dual-Radar/assets/109153347/ae10f459-3c1f-4036-8e94-fd9162276ff2)

**Comment by c-yyyy** [comment]
> 请问您这边有没有遇到radar模型推理阶段出现bbox角度和位置偏移的问题呢？即使使用lidar模型也存在这个现象。我遇到一个奇怪的现象在一定范围内，bbox会偏差90度，但是不在这个范围内的则是正常的。 ![12344](https://private-user-images.githubusercontent.com/109153347/332623905-ae10f459-3c1f-4036-8e94-fd9162276ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjQyMDQsIm5iZiI6MTcxNzQyMzkwNCwicGF0aCI6Ii8xMDkxNTMzNDcvMzMyNjIzOTA1LWFlMTBmNDU5LTNjMWYtNDAzNi04ZTk0LWZkOTE2MjI3NmZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNDExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODJmOTNlNjVkMWU5ZWJiNGQxMWQzZTNjOTM5NWJiZjhhZTE2ZjgyOTBhNGVkYThkZmRiYjVkZGY5MGQ3ZjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vY-Y1dq4HvbVEW6LbXjF42vghqvgXM3IR6WKbr3jCEw)



> 请问您这边有没有遇到radar模型推理阶段出现bbox角度和位置偏移的问题呢？即使使用lidar模型也存在这个现象。我遇到一个奇怪的现象在一定范围内，bbox会偏差90度，但是不在这个范围内的则是正常的。 ![12344](https://private-user-images.githubusercontent.com/109153347/332623905-ae10f459-3c1f-4036-8e94-fd9162276ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjQzNzAsIm5iZiI6MTcxNzQyNDA3MCwicGF0aCI6Ii8xMDkxNTMzNDcvMzMyNjIzOTA1LWFlMTBmNDU5LTNjMWYtNDAzNi04ZTk0LWZkOTE2MjI3NmZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNDE0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGI3NTc5YWU0ZDBmYjlmNjkyMTJiYzk3MDc0NTgzYmEyZjQ2NGJjMmM2MTc1MjUzMjFiOTk3NjBiNzU2Njg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sGxt7AEPeyt6aP6MUxRsvHKKnGrG2PoV-0a_3t84Vsw)

你是用什么框架做的

**Comment by c-yyyy** [comment]
> 请问您这边有没有遇到radar模型推理阶段出现bbox角度和位置偏移的问题呢？即使使用lidar模型也存在这个现象。我遇到一个奇怪的现象在一定范围内，bbox会偏差90度，但是不在这个范围内的则是正常的。 ![12344](https://private-user-images.githubusercontent.com/109153347/332623905-ae10f459-3c1f-4036-8e94-fd9162276ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjQzNzAsIm5iZiI6MTcxNzQyNDA3MCwicGF0aCI6Ii8xMDkxNTMzNDcvMzMyNjIzOTA1LWFlMTBmNDU5LTNjMWYtNDAzNi04ZTk0LWZkOTE2MjI3NmZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNDE0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGI3NTc5YWU0ZDBmYjlmNjkyMTJiYzk3MDc0NTgzYmEyZjQ2NGJjMmM2MTc1MjUzMjFiOTk3NjBiNzU2Njg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sGxt7AEPeyt6aP6MUxRsvHKKnGrG2PoV-0a_3t84Vsw)

你是用什么框架做的

**Comment by Bryceder** [comment]
就是使用的openpcdet框架，后来我发现是框架内数据处理有角度没有处理好吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adept-thu/Dual-Radar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月3日(星期一) 晚上10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adept-thu/Dual-Radar] arbe、ars、Lidar三种模态点云保存时对应坐标系 (Issue #13)





  
请问您这边有没有遇到radar模型推理阶段出现bbox角度和位置偏移的问题呢？即使使用lidar模型也存在这个现象。我遇到一个奇怪的现象在一定范围内，bbox会偏差90度，但是不在这个范围内的则是正常的。 
  
你是用什么框架做的
