### ISSUE TITLE
Question about radar detection performance

### ISSUE THREAD

**Issue by Toytiny** [adept-thu/Dual-Radar#4]
Hi authors,

Great work! Thanks for your diligence. This dataset would greatly benefit the whole community.

 In Table 4-table 8, we notice that when the input data is radar point clouds or camera+radar, the mAP@0.25 on the pedestrians and cyclists is unsatisfactory, i.e., almost close to 0. On the contrary, the mAP of the car section seems more normal and comparable to LiDARs. Would you like to explain a bit little about that? As shown in the gif figures, the 4D radar point clouds from either Arbe or ARS548, are fairly dense and would possibly serve for small object detection, e.g., people or bicycles. However, the results shown on the table do not validate this.

**Comment by lwangthu** [comment]
Sorry to reply late. We also have the same confusion. The detection performance of radar point clouds for pedestrians and cyclists is very poor. We use popular detection algorithms in the field and provide training codes and models. Welcome to test them. One possible reason is that pedestrians and cyclists are small objects with weak millimeter wave reflection, resulting in poor detection.
