### ISSUE TITLE
Data request License is under edit mode !!!! (dangerous issue)

### ISSUE THREAD

**Issue by Ianpengg** [adept-thu/Dual-Radar#5]
Hello, I have a question regarding the license.doc: it appears to be a contract between two parties. It seems that someone has directly modified the original document with their personal information. I would suggest setting the editing permission to 'read-only' to prevent further alterations. Thank you for your assistance

Current version
![image](https://github.com/adept-thu/Dual-Radar/assets/88025855/5ebf8d04-201f-4abc-a399-a0bd7131978c)

The original version
![image](https://github.com/adept-thu/Dual-Radar/assets/88025855/db44a27e-621d-47f0-97a4-b14190fba4e9)

**Comment by liulin813** [comment]
thank you for your comments very much
